# Generated by Django 4.2.14 on 2024-08-01 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0005_alter_file_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="file", name="permissions",),
        migrations.AddField(
            model_name="file",
            name="shared_with",
            field=models.ManyToManyField(
                related_name="shared_files", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
